# Generated by Django 4.2 on 2024-09-06 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorymanagement', '0003_productcategory_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_column='name', max_length=56)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('price', models.IntegerField(db_column='price')),
                ('status', models.BooleanField(db_column='status', default='A')),
                ('stock', models.IntegerField(db_column='stock', default=0)),
                ('file_path', models.FileField(blank=True, db_column='filePath', null=True, upload_to='files/')),
                ('created_by', models.CharField(db_column='createdBy', max_length=16)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='categorymanagement.productcategory')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], db_column='discountType', max_length=10)),
                ('value', models.DecimalField(db_column='value', decimal_places=2, max_digits=2)),
                ('start_date', models.DateField(db_column='startDate')),
                ('end_date', models.DateField(db_column='endDate')),
                ('created_by', models.CharField(db_column='createdBy', max_length=16)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='categorymanagement.productcategory')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='productmanagement.product')),
            ],
            options={
                'db_table': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(db_column='rating')),
                ('review', models.TextField(blank=True, db_column='review', null=True)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='productmanagement.product')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProductRatings',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
