# Generated by Django 4.2 on 2024-09-06 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.custom_model


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_path',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('file_path', models.CharField(db_column='filePath', max_length=256)),
                ('product_image_no', models.BooleanField(db_column='productImageNo', default=1)),
                ('created_by', models.CharField(db_column='createdBy', max_length=16)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productmanagement.product')),
            ],
            options={
                'db_table': 'ProductImages',
                'unique_together': {('product', 'product_image_no')},
            },
            bases=(utils.custom_model.DynamicValidationMixin, models.Model),
        ),
    ]
