# Generated by Django 4.2 on 2024-09-03 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(db_column='fullName', max_length=56)),
                ('phone_number', models.CharField(db_column='phoneNo', max_length=10)),
                ('pincode', models.CharField(db_column='pincode', max_length=8)),
                ('state', models.CharField(db_column='state', max_length=56)),
                ('city', models.CharField(db_column='city', max_length=56)),
                ('address', models.TextField(db_column='address')),
                ('landmark', models.CharField(blank=True, db_column='landmark', max_length=256, null=True)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], db_column='addressType', default='Home', max_length=8)),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
    ]
