# Generated by Django 4.2 on 2024-09-04 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_address_address_type_alter_address_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='address',
            name='modifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
