# Generated by Django 4.2 on 2024-09-16 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_address_createdat_alter_address_modifiedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('email', models.CharField(db_column='Email', max_length=56)),
                ('count', models.IntegerField(db_column='Count', default=1)),
            ],
            options={
                'db_table': 'OtpRequests',
            },
        ),
    ]
