# Generated by Django 4.2 on 2024-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_otprequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequests',
            name='count',
            field=models.IntegerField(db_column='Count', default=0),
        ),
    ]
