# Generated by Django 4.2 on 2024-09-17 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_alter_otprequests_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(db_column='Name', default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(db_column='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(db_column='AddressType', default='Home', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_column='City', max_length=56),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(db_column='Name', max_length=56),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, db_column='Landmark', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(db_column='Phone', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(db_column='Pincode', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(db_column='State', max_length=56),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='DOB', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(db_column='Email', max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('N/A', 'N/A')], db_column='Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(db_column='IsStaff', default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='loyalty_points',
            field=models.IntegerField(db_column='LoyalityPoints', default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(db_column='ModifiedAT', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, db_column='Photo', null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.JSONField(db_column='Roles', default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], db_column='Status', default='A', max_length=1),
        ),
    ]
