# Generated by Django 4.2 on 2024-09-19 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='createdAt',
            field=models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='address',
            name='modifiedAt',
            field=models.DateTimeField(db_column='ModifiedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(db_column='ModifiedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='otprequests',
            name='createdAt',
            field=models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='otprequests',
            name='modifiedAt',
            field=models.DateTimeField(db_column='ModifiedAt', default=django.utils.timezone.now),
        ),
    ]
