# Generated by Django 4.2 on 2024-09-04 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('status', models.BooleanField(db_column='status', default=True)),
                ('parent_category', models.ForeignKey(blank=True, db_column='parentCategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_categories', to='categorymanagement.productcategory')),
            ],
            options={
                'db_table': 'ProductCategories',
            },
        ),
    ]
