# Generated by Django 4.2 on 2024-09-04 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
