# Generated by Django 4.2 on 2024-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0002_alter_productcategory_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.CharField(db_column='created_by', default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_column='name', max_length=255, unique=True),
        ),
    ]
