# Generated by Django 4.2 on 2024-09-19 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0003_productcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='createdAt',
            field=models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modifiedAt',
            field=models.DateTimeField(db_column='ModifiedAt', default=django.utils.timezone.now),
        ),
    ]
